// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mmevbotzfbbadzebzekq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1tZXZib3R6ZmJiYWR6ZWJ6ZWtxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMTAxNDYsImV4cCI6MjA1Njg4NjE0Nn0.hKjiMh74DdvO49STBaTK7KLM95rUIaXsp2MSp8fBJM8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);